In [1]:
import pandas as pd
import numpy as np

In [2]:
movies_df = pd.read_csv(r'E:\Pyhton code\Data Sets\archive\ml-latest-small\movies.csv',usecols=['movieId','title'], dtype={'movieId':'int32','title':'str'})
rating_df = pd.read_csv(r'E:\Pyhton code\Data Sets\archive\ml-latest-small\ratings.csv', usecols=['userId','movieId','rating'], dtype={'userId':'int32','movieId':'int32','rating':'float32'})

In [3]:
movies_df.head()

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [4]:
rating_df.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [5]:
df = pd.merge(rating_df, movies_df, on='movieId')
df.head()

   userId  movieId  rating                        title
0       1        1     4.0             Toy Story (1995)
1       1        3     4.0      Grumpier Old Men (1995)
2       1        6     4.0                  Heat (1995)
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)
4       1       50     5.0   Usual Suspects, The (1995)

In [6]:
df.shape

(100836, 4)

In [9]:
combine_movie_rating = df.dropna(axis=0, subset= ['title'])
movie_rating_count = (combine_movie_rating.
                      groupby(by=['title'])['rating'].
                      count().
                      reset_index().
                      rename(columns={'rating':'totalRatingCount'})
                      [['title','totalRatingCount']]
                    )
movie_rating_count.head()

                                     title  totalRatingCount
0                               '71 (2014)                 1
1  'Hellboy': The Seeds of Creation (2004)                 1
2                   'Round Midnight (1986)                 2
3                      'Salem's Lot (2004)                 1
4                'Til There Was You (1997)                 2

In [10]:
rating_with_totalRatingCount = combine_movie_rating.merge(movie_rating_count, left_on='title',right_on='title', how ='left')
rating_with_totalRatingCount.head()

   userId  movieId  rating                        title  totalRatingCount
0       1        1     4.0             Toy Story (1995)               215
1       1        3     4.0      Grumpier Old Men (1995)                52
2       1        6     4.0                  Heat (1995)               102
3       1       47     5.0  Seven (a.k.a. Se7en) (1995)               203
4       1       50     5.0   Usual Suspects, The (1995)               204

In [11]:
pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(movie_rating_count['totalRatingCount'].describe())

count   9719.000
mean      10.375
std       22.406
min        1.000
25%        1.000
50%        3.000
75%        9.000
max      329.000
Name: totalRatingCount, dtype: float64

In [12]:
popularity_threshold = 50
rating_popular_movie = rating_with_totalRatingCount.query('totalRatingCount >= @popularity_threshold')
rating_popular_movie.head()

   userId  movieId  rating                        title  totalRatingCount
0       1        1   4.000             Toy Story (1995)               215
1       1        3   4.000      Grumpier Old Men (1995)                52
2       1        6   4.000                  Heat (1995)               102
3       1       47   5.000  Seven (a.k.a. Se7en) (1995)               203
4       1       50   5.000   Usual Suspects, The (1995)               204

In [13]:
rating_popular_movie.shape

(41362, 5)

In [14]:
#create a pivot matrix
movie_features_df = rating_popular_movie.pivot_table(index='title', columns='userId', values='rating').fillna(0)
movie_features_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You (1999),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,3.000,0.000,5.000,0.000,0.000,0.000,0.000,0.000
12 Angry Men (1957),0.000,0.000,0.000,5.000,0.000,0.000,0.000,0.000,0.000,0.000,...,5.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2001: A Space Odyssey (1968),0.000,0.000,0.000,0.000,0.000,0.000,4.000,0.000,0.000,0.000,...,0.000,0.000,5.000,0.000,0.000,5.000,0.000,3.000,0.000,4.500
28 Days Later (2002),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.500,0.000,5.000
300 (2007),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.000,...,0.000,0.000,0.000,0.000,3.000,0.000,0.000,5.000,0.000,4.000

In [17]:
from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(movie_features_df.values)

from sklearn.neighbors import NearestNeighbors

model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(movie_features_df_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [18]:
movie_features_df.shape

(450, 606)

In [19]:
query_index = np.random.choice(movie_features_df.shape[0])
print(query_index)
distances, indices = model_knn.kneighbors(movie_features_df.iloc[query_index,:].values.reshape(1,-1),n_neighbors=6)

302

In [21]:
movie_features_df.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
10 Things I Hate About You (1999),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,3.000,0.000,5.000,0.000,0.000,0.000,0.000,0.000
12 Angry Men (1957),0.000,0.000,0.000,5.000,0.000,0.000,0.000,0.000,0.000,0.000,...,5.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
2001: A Space Odyssey (1968),0.000,0.000,0.000,0.000,0.000,0.000,4.000,0.000,0.000,0.000,...,0.000,0.000,5.000,0.000,0.000,5.000,0.000,3.000,0.000,4.500
28 Days Later (2002),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.500,0.000,5.000
300 (2007),0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,3.000,...,0.000,0.000,0.000,0.000,3.000,0.000,0.000,5.000,0.000,4.000

In [22]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendation for {0}; \n'.format(movie_features_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, movie_features_df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendation for Patriot, The (2000);

1: Gladiator (2000), with distance of 0.5324332118034363:
2: Gone in 60 Seconds (2000), with distance of 0.5399603247642517:
3: Star Wars: Episode III - Revenge of the Sith (2005), with distance of 0.5474470853805542:
4: X-Men (2000), with distance of 0.5497115254402161:
5: Mask of Zorro, The (1998), with distance of 0.5546260476112366:

Report:

- Title: Movie Recommendation Using KNN

- Dataset: (100836, 4)

- Methodology:
  - Data Loading and Analysis: Load the dataset and analyze the data to understand the distribution of ratings and user behavior.
  - KNN Implementation: 
    - Combined user rating of movies into a user-item matrix. We used cosine similarity to measure the similarity between users based on their ratings on movies. We then applied the KNN algorithm to find the k nearest neighbors for each user.
    - Prediction: For each user, we identified their k nearest neighbors and predicted their ratings for movies they haven't rated yet by taking the average rating from their neighbors.

- Results:
Recommendation for Patriot, The (2000); 

- 1: Gladiator (2000), with distance of 0.5324332118034363:
- 2: Gone in 60 Seconds (2000), with distance of 0.5399603247642517:
- 3: Star Wars: Episode III - Revenge of the Sith (2005), with distance of 0.5474470853805542:
- 4: X-Men (2000), with distance of 0.5497115254402161:
- 5: Mask of Zorro, The (1998), with distance of 0.5546260476112366: